# Generated by Django 5.1.4 on 2025-03-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grades',
            field=models.JSONField(default=dict),
        ),
    ]
